### PR TITLE
feat: Expanding folded lines

### PR DESCRIPTION
**Pull request by cjboy76**
This PR for feature expanding folded lines, it is adapted to Vue 2, Vue 3 and both output-format.

### CODE REVIEW

**Comment by Shimada666** [comment]
Thank you very much for your work! I tried it out and the functionality is working fine, but there is only one small drawback. When the passed-in prop value changes, the generated diff content doesn't change accordingly. I think it might be necessary to regenerate the diff content. Could you fix it?

**Comment by cjboy76** [comment]
Sure I'll look into that. 👍

**Comment by cjboy76** [comment]
@Shimada666 Could you guide me setting up this repo and install dependencies? I'd like to access the correct version of vue but postinstall and dependency import is kind of confused.

**Comment by Shimada666** [comment]
I don't quite understand.. Could you be more specific?

**Comment by cjboy76** [comment]
It turns out some kind of runtime dependency resolve error in Github Codespaces, l switched to VSCode later and problem solved!
Finally I decide to manipulate props to local state for performing mutable state and expanding lines, it is tricky but only way I come up with.🥲

**Comment by Shimada666** [comment]
> It turns out some kind of runtime dependency resolve error in Github Codespaces, l switched to VSCode later and problem solved! Finally I decide to manipulate props to local state for performing mutable state and expanding lines, it is tricky but only way I come up with.🥲

Actually, I don't think it's that complicated. I previously cloned your repository. The commit ID is a73ad48. Just by adding a watch function, we can achieve responsive updates , like this: 

```typescript
const raw = computed(() =>
  isUnifiedViewer.value
    ? createUnifiedDiff(oldString.value, newString.value, props.language, props.diffStyle, props.context)
    : createSplitDiff(oldString.value, newString.value, props.language, props.diffStyle, props.context),
)
let diffChange = reactive(raw.value)
watch(() => props, () => {
  diffChange = reactive(raw.value)
}, { deep: true })
```
It's simple, but it can work properly. What do you think? 😉

**Comment by cjboy76** [comment]
I agreed but there is one thing, 
I tried doing this previously and I tested it out in both `vue3-playground` and `vue2.7-playground`, I found that it somehow wasn't working in `vue2.7-playground`(which is so weird).🤨
Wondering is it just me running into this issue or did you test it out in `vue2.7-playground` and it worked fine?

**Comment by Shimada666** [comment]
Sorry, I didn't realize that reassigning reactive data would lose reactivity in Vue 2. So I changed the logic of reassignment and used ref instead. Now it can work properly, like this: 😃

```typescript
const raw = computed(() =>
  isUnifiedViewer.value
    ? createUnifiedDiff(oldString.value, newString.value, props.language, props.diffStyle, props.context)
    : createSplitDiff(oldString.value, newString.value, props.language, props.diffStyle, props.context),
)
const diffChange = ref(raw.value)
watch(() => props, () => {
  diffChange.value = raw.value
}, { deep: true })
```

**Comment by cjboy76** [comment]
The first time I knew about it, it seems like there's still some tricks I need to keep up while building universal components.🤯
Thanks for the advise!

**Comment by Shimada666** [comment]
Great job! It's working fine in most cases. However, I've still found a small bug where the first line is never collapsed in line-by-line mode. Could you please fix it once again?

image

**Comment by cjboy76** [comment]
I kind of forget the intention why writing that conditional case to exclude the first line,
Appreciate your reminder.

**Comment by Shimada666** [comment]
Looks great! Thank you for your work. Lastly, could you squash these commits into one? I'll merge this PR and release it soon.

**Comment by cjboy76** [comment]
No problem. 👍

**Pull request merged**
