### PR TITLE
Added Go to Next Difference feature - vue3.

### PR DESCRIPTION
**Pull request by QusaiSabri**
### Go to Next Difference
Added two buttons to the header component that allow users to navigate through diffs sequentially. This feature highlights the current diff and scrolls to it, making the user experience much better specially on longer files.

I would appreciate any feedback on the code and functionality.

### Testing:
- **Local Testing**: I did a thorough testing in my local dev environment with multiple scenarios to ensure the feature works as expected.
- **Browsers Tested**: I verified the functionality across several browsers including Chrome, Firefox, and Edge.
- **Vue 3 vs 2**: Ensured that the changes do not affect Vue 2 functionality.

Here is a screenshot of the feature:
image

### CODE REVIEW

**Comment by Shimada666** [comment]
@09473ZH

**Comment by 09473ZH** [comment]
@QusaiSabri, thank you for your awesome work! However, I noticed that it doesn't seem to work with the "Line by Line" format. Is that what you expected?

**Comment by QusaiSabri** [comment]
Thanks for the review and excellent feedback, @09473ZH . I have updated the PR to add support for 'Line by Line' and made sure to use ESLint to format the code before pushing.

Once this PR is merged, I will work on adding support for Vue2 through a second PR.

**Comment by 09473ZH** [comment]
https://github.com/Shimada666/v-code-diff/assets/43346380/e674a270-dc82-4b16-96e2-00b81052e795

That is nice! Everything works well, but there's a little inconvenience. When I click on the next line, the header slides up. If I want to continue, I have to scroll back up to the top line. (As shown in the demo) How exactly are you using it? If we need to add this feature, it seems like having a fixed header would be better.Again,thanks for all your hard work! :)

**Comment by 09473ZH** [comment]
I've already submitted a PR for this issue (https://github.com/Shimada666/v-code-diff/pull/140). Maybe it's resolved now. After you update the code, I'll test it again. :)

**Comment by 09473ZH** [comment]
> demo.mp4 
> That is nice! Everything works well, but there's a little inconvenience. When I click on the next line, the header slides up. If I want to continue, I have to scroll back up to the top line. (As shown in the demo) How exactly are you using it? If we need to add this feature, it seems like having a fixed header would be better.Again,thanks for all your hard work! :)

I've already submitted a PR for this issue (https://github.com/Shimada666/v-code-diff/pull/140). It works well for me now. After you update the code, test it again :)"

**Comment by QusaiSabri** [comment]
@09473ZH  That's awesome! Thank you! All works well now as long as the **code-diff-view** div has a specified height.

Ignore my comment about vue2, I tested it and It works great with both Vue2 & 3.

**Comment by Shimada666** [comment]
@QusaiSabri Thanks for your work!

**Comment by 09473ZH** [comment]
https://github.com/Shimada666/v-code-diff/issues/117

**Pull request merged**
